'use client';
import React from 'react';
import { Calendar, Eye, ListChecks, Megaphone } from 'lucide-react';
import { Exam } from './exam.types';
import { examTypeLabel, formatExamDate } from './exam.helpers';
import ExamStatusBadge from './ExamStatusBadge';

interface Props { exams: Exam[]; onPublish:(exam:Exam)=>void; onOpen:(exam:Exam)=>void; onResults:(exam:Exam)=>void; }
export default function ExamTable({ exams,onPublish,onOpen,onResults }:Props){
 return <div className="overflow-hidden rounded-3xl border border-white/[0.08] bg-white/[0.025]"><div className="overflow-x-auto"><table className="w-full min-w-[950px]"><thead><tr className="border-b border-white/[0.06] bg-white/[0.015]"><Th>Exam</Th><Th>Type</Th><Th>Class / Batch</Th><Th>Date</Th><Th>Marks</Th><Th>Status</Th><Th align="right">Actions</Th></tr></thead><tbody>{exams.map(exam=><tr key={exam._id} className="border-b border-white/[0.045] hover:bg-white/[0.025]"><td className="px-5 py-4"><p className="text-xs font-bold text-white">{exam.title}</p><p className="mt-0.5 text-[10px] text-white/30">{exam.subject}</p></td><td className="px-4 py-4 text-[10px] font-semibold text-white/55">{examTypeLabel(exam.type)}</td><td className="px-4 py-4"><p className="text-xs text-white/70">Class {exam.className}</p><p className="mt-0.5 text-[10px] text-white/30">{exam.batch || exam.group || 'All eligible students'}</p></td><td className="px-4 py-4 text-[10px] text-white/50"><span className="inline-flex items-center gap-1.5"><Calendar size={12} className="text-[#adc6ff]"/>{formatExamDate(exam.examDate)}</span></td><td className="px-4 py-4 text-right font-mono text-xs font-bold text-white">{exam.totalMarks}</td><td className="px-4 py-4"><ExamStatusBadge status={exam.status}/></td><td className="px-4 py-4"><div className="flex justify-end gap-1.5"><button title="View exam" onClick={()=>onOpen(exam)} className="rounded-xl border border-white/10 p-2 text-white/45 hover:bg-white/10 hover:text-white"><Eye size={14}/></button>{exam.status==='published' && <button title="Enter results" onClick={()=>onResults(exam)} className="rounded-xl border border-[#adc6ff]/10 bg-[#adc6ff]/5 p-2 text-[#adc6ff] hover:bg-[#adc6ff]/10"><ListChecks size={14}/></button>}{exam.status==='draft' && <button title="Publish exam" onClick={()=>onPublish(exam)} className="rounded-xl border border-[#6ffbbe]/10 bg-[#6ffbbe]/5 p-2 text-[#6ffbbe] hover:bg-[#6ffbbe]/10"><Megaphone size={14}/></button>}</div></td></tr>)}</tbody></table></div></div>
}
function Th({children,align='left'}:{children:React.ReactNode;align?:'left'|'right'}){return <th className={`px-4 py-3 text-${align} text-[9px] font-bold uppercase tracking-wider text-white/30`}>{children}</th>}
