'use client';
import React from 'react';
import { Trophy } from 'lucide-react';
// import { DashboardTableWrapper, EmptyState } from '@/components/dashboard/common';
 import { DashboardTableWrapper, EmptyState } from '@/components/dashboard/common';
import { LeaderboardRow } from './result.types';
import { formatPercentage } from './result.helpers';

export default function LeaderboardTable({ rows, overall=false }: { rows: LeaderboardRow[]; overall?: boolean }) {
 return <DashboardTableWrapper><div className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr className="border-b border-white/10 bg-white/[0.015]"><th className="px-5 py-3 text-left text-[9px] uppercase text-white/30">Rank</th><th className="px-5 py-3 text-left text-[9px] uppercase text-white/30">Student</th><th className="px-5 py-3 text-right text-[9px] uppercase text-white/30">{overall?'Average':'Percentage'}</th>{!overall&&<th className="px-5 py-3 text-right text-[9px] uppercase text-white/30">Marks</th>}<th className="px-5 py-3 text-right text-[9px] uppercase text-white/30">{overall?'Exams':'Grade'}</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.student?._id}-${row.rank}`} className="border-b border-white/5 hover:bg-white/[0.025]"><td className="px-5 py-4"><span className={`inline-flex h-8 min-w-8 items-center justify-center rounded-xl ${row.rank<=3?'bg-amber-400/10 text-amber-300':'bg-white/5 text-white/50'} text-xs font-black`}>{row.rank}</span></td><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center overflow-hidden rounded-xl bg-gradient-to-br from-[#adc6ff]/15 to-[#6ffbbe]/10 text-xs font-black text-[#adc6ff]">{row.student?.photo?<img src={row.student.photo} alt="" className="h-full w-full object-cover"/>:row.student?.name?.charAt(0)||'S'}</div><div><p className="text-xs font-bold text-white">{row.student?.name||'Unknown'}</p><p className="text-[9px] text-white/30">Class {row.student?.className||'—'}{row.student?.batch?` · ${row.student.batch}`:''}</p></div></div></td><td className="px-5 py-4 text-right font-mono text-xs font-black text-[#6ffbbe]">{formatPercentage(overall?row.averagePercentage:row.percentage)}</td>{!overall&&<td className="px-5 py-4 text-right font-mono text-xs text-white/70">{row.totalMarks ?? '—'} / {row.totalFullMarks ?? '—'}</td>}<td className="px-5 py-4 text-right text-xs font-bold text-white/60">{overall?row.totalExams:row.grade}</td></tr>)}</tbody></table></div>{!rows.length&&<EmptyState title="No leaderboard data" description="No published result data is available for this view."/>}</DashboardTableWrapper>;
}
